### ISSUE TITLE
Keren 😎👍

### ISSUE THREAD

**Issue by Muhamad700** [AdityaGans2542/AdityaRDP#1]
Keren 😎👍

**Comment by EmanSaputra** [comment]
![20210501_105750](https://user-images.githubusercontent.com/76545003/116788145-460c5700-aad2-11eb-8e28-2009ba3fc6c7.png)
This Script Original By Me! (https://github.com/EmanSaputra/FreeRDP)
"Windows Server 2019 By NaufalCream"

**Comment by EmanSaputra** [comment]
![20210501_104951](https://user-images.githubusercontent.com/76545003/116788154-51f81900-aad2-11eb-8cec-0c044f3f6b2b.png)
